name: snippet-dev

services:
  app:
    build:
      target: development
    image: ${IMAGE:-snippet}:${TAG:-local}-development
    environment:
      ENVIRONMENT: development
    command:
      - sleep
      - infinity
    volumes:
      - vendor-development:/app/vendor
      - node-development:/app/node_modules
